config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  post 'create_user', to: 'users#create'
  root :to =>  'welcome#index'
  resources :chatrooms, param: :slug
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages
  has_many :chatrooms, through: :messages
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      ActionCable.server.broadcast 'chats',
        topic: @chatroom.topic,
        id: @chatroom.id
      head :ok
    else
      respond_to do |format|
        flash[:notice] = {error: ["YA EXISTE UN CHATROOM CON ESE NOMBRE"]}
        format.html { redirect_to new_chatroom_path }
      end
    end
  end

  def show
  	@chatroom = Chatroom.find(params[:slug])
    @message = Message.new
  end

  private
    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    message.user = User.find(cookies[:user_id])
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.content,
        user: message.user.username
      head :ok
    end
  end

  private

    def message_params
      params.require(:message).permit(:content, :chatroom_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
  	if params[:username].present?
  	  if User.where(username: params[:username]).first.nil?
  	  	cookies['user_id'] =  User.create(username: params[:username]).id
  	  	redirect_to chatrooms_path
  	  else
  	  	cookies['user_id'] = User.select(:id).where(username: params[:username]).first.id
  	  	redirect_to chatrooms_path 
  	  end
  	else
      flash[:notice] = {error: "DEBE INGRESAR EL NOMBRE DE USUARIO"}
      redirect_to root_path
  	end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chatrooms/_chatroom.html.erb
<div class="col-sm-6 col-md-4 col-lg-3 mt-4">
  <div class="card" style="width: 20rem;">
    <img class="card-img-top" >
    <div class="card-body">
      <h1><%= chatroom.topic %></h1>
      <p class="card-text">LOREM IMPSM</p>
      <%= link_to 'IR AL CHAT', chatroom_path(chatroom), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/chatrooms/_chatroom_form.html.erb
<div class="row">
  <%= form_for chatroom, remote: true do |f| %>

    <div class="col-md-11">
      <div class="input-group">
        <span class="input-group-addon">TEMA:</span>
        <%= f.text_field :topic, class: "form-control"%>
      </div>
    </div>

    <div class="col-md-1">
      <%= f.submit 'CREAR SALA DE CHAT', class: "btn btn-primary", id: "create-chatroom" %>
    </div>

  <% end %>
</div>

app/views/chatrooms/index.html.erb
<div class="container" id="chatroom-title">

  <center><h1>Salas de Chat disponibles</h1></center>
  <br />

  <div class="row" id="chatrooms">
    <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
  </div>

  <br />

  <% if !flash[:notice].nil? %>
    <div class="alert alert-success"> 
      <center><%= flash[:notice]['error'] %></center>
    </div>
  <% end %>

  <div id="chatroom-errors"></div>
    
  <div class="row" id="chats">      
    <% if @chatrooms.any? %>
      <%= render @chatrooms%>
    <%else %>        
      <p>SE EL PRIMERO EN CREAR UNA SALA DE CHAT</p>
    <% end %>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

<div class="panel panel-default">
  <% if @chatroom.messages.any? %>
    <div class="panel-body" id="messages">
      <%= render partial: 'messages/message', collection: @chatroom.messages%>
    </div>
  <%else%>
    <div class="panel-body" id="messages">
      <%= render partial: 'messages/message', collection: @chatroom.messages%>
    </div>
  <%end%>
</div>

  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableExample</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p><strong><%=message.user.username%>:</strong> <%=message.content%></p>

app/views/messages/_message_form.html.erb
<div class="row">
  <%= form_for message, remote: true do |f| %>

    <div class="col-md-11">
      <%= f.text_area :content, class: "form-control", data: {textarea: "message"}, placeholder: 'INGRESE SU MENSAJE' %>
    </div>
    <div class="col-md-1">
      <%= f.hidden_field :chatroom_id, value: chatroom.id %>
      <%= f.submit "ENVIAR", class: "btn btn-primary", data: {send: "message"} %>
    </div>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <center><h1>CHAT</h1></center>
    <center><p>USANDO RUBY ON RAILS CON ACTION CABLE Y REDIS DB</p></center>
  </div>

  <% if !flash[:notice].nil? %>
    <div class="alert alert-danger"> 
      <center><%= flash[:notice]['error'] %></center>
    </div>
  <% end %>

  <center><h1>INGRESE USANDO SU NOMBRE DE USUARIO</h1></center>
  <br />

  <div class="row">
    <%= form_tag create_user_path do -%>	 
	    <div class="col-md-10">
	       <div class="form-group">
	       	<%= text_field_tag :username, '', class: 'form-control', placeholder: 'INGRESE EL NOMBDE DE USUARIO' %>
	       </div>
	    </div>
	    <div class="col-md-2">
	       <%= submit_tag 'INGRESAR', class: 'btn btn-primary' %>
	    </div> 
    <% end -%>
  </div>

</div>